### ISSUE TITLE
مشكلة بالايفون

### ISSUE THREAD

**Issue by amsmadi** [emadmahdi/KODI#76]
مرحبا اخ عماد

عندي مشكلة بالايفون على جميع اصدارات كودي رقم 18
عندما احاول الدخول على اضافة
arabic videos
تظهر رسالة خطأ كالتالي

Uname 1232 platform خطأ
IOError: [Error 10] No Child processes

نسخة كودي المستخدمة اخيرا 18.2

شكرا مقدما على الشغل الكبير

**Comment by emadmahdi** [comment]
مشكلتك هي في لغة بايثون التي تأتي مع كودي ... حاول تثبيت اخر اصدار كودي 18 ... قد يحل المشكلة ... حمل ملف اصدار رقم 18.9 من هذا الرابط

http://mirrors.kodi.tv/releases/

اذا المشكة لم تحل فاخبرني اذا كنت تستطيع تغيير ملفات ابل ... وهل جهازك 
jailbroken
وهل عندك
root

**Comment by amsmadi** [comment]
تمت التجربة على جميع اصدارات رقم 18
ومنها 18.9 وتعطي الخطأ ذاته.

نعم استطيع تغيير اي ملف
جهازي jailbroken

شكرا جزيلا

**Comment by emadmahdi** [comment]
هل تستطيع ان ترسل لي سجل الاخطاء
kodi.log

اذا ليست لديك خبرة في الملفات 
هناك اضافات لكودي ممكن ترسل لي بواسطتها سجل الاخطاء

**Comment by amsmadi** [comment]
نعم استطيع، تفضل

2021-04-02 01:08:11.512 T:6173683712   ERROR: Traceback (most recent call last):
                                              File "/private/var/mobile/Containers/Data/Application/C806E156-512C-4B60-AD7C-36567EF5BB19/Library/Preferences/Kodi/addons/plugin.video.arabicvideos/arabicvideos/__init__.py", line 10, in <module>
                                                try: MAIN()
                                              File "/private/var/mobile/Containers/Data/Application/C806E156-512C-4B60-AD7C-36567EF5BB19/Library/Preferences/Kodi/addons/plugin.video.arabicvideos/arabicvideos/LIBRARY.py", line 280, in MAIN
                                                else: results = MAIN_DISPATCHER(type,name88,url99,mode,image99,page99,text,context)
                                              File "/private/var/mobile/Containers/Data/Application/C806E156-512C-4B60-AD7C-36567EF5BB19/Library/Preferences/Kodi/addons/plugin.video.arabicvideos/arabicvideos/LIBRARY.py", line 334, in MAIN_DISPATCHER
                                                elif mode2==26: import MENUS 		; results = MENUS.MAIN(mode,url,text)
                                              File "/private/var/mobile/Containers/Data/Application/C806E156-512C-4B60-AD7C-36567EF5BB19/Library/Preferences/Kodi/addons/plugin.video.arabicvideos/arabicvideos/MENUS.py", line 10, in MAIN
                                                if   mode==260: results = MENU()
                                              File "/private/var/mobile/Containers/Data/Application/C806E156-512C-4B60-AD7C-36567EF5BB19/Library/Preferences/Kodi/addons/plugin.video.arabicvideos/arabicvideos/MENUS.py", line 24, in MENU
                                                color = SHOW_MESSAGES(False)
                                              File "/private/var/mobile/Containers/Data/Application/C806E156-512C-4B60-AD7C-36567EF5BB19/Library/Preferences/Kodi/addons/plugin.video.arabicvideos/arabicvideos/MENUS.py", line 234, in SHOW_MESSAGES
                                                payload = {'user':dummyClientID(32)}
                                              File "/private/var/mobile/Containers/Data/Application/C806E156-512C-4B60-AD7C-36567EF5BB19/Library/Preferences/Kodi/addons/plugin.video.arabicvideos/arabicvideos/LIBRARY.py", line 1300, in dummyClientID
                                                hostname = platform.node()			# empc12/localhosting
                                              File "/Users/Shared/jenkins/workspace/IOS-ARM64_Leia/tools/depends/xbmc-depends/iphoneos11.0_arm64-target-release/lib/python2.7/platform.py", line 1275, in node
                                              File "/Users/Shared/jenkins/workspace/IOS-ARM64_Leia/tools/depends/xbmc-depends/iphoneos11.0_arm64-target-release/lib/python2.7/platform.py", line 1232, in uname
                                              File "/Users/Shared/jenkins/workspace/IOS-ARM64_Leia/tools/depends/xbmc-depends/iphoneos11.0_arm64-target-release/lib/python2.7/platform.py", line 967, in _syscmd_uname
                                            IOError: [Errno 10] No child processes
2021-04-02 01:08:11.544 T:6165082112   ERROR: GetDirectory - Error getting plugin://plugin.video.arabicvideos/
2021-04-02 01:08:11.549 T:6165655552   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.arabicvideos/) failed

**Comment by emadmahdi** [comment]
اريد الملف كامل

**Comment by amsmadi** [comment]
تفضل

https://gofile.io/d/37zM66

**Comment by emadmahdi** [comment]
مشكلتك واضح انها من بايثون ولكني تجاوزتها في برنامجي لاني متأكذ ان هناك غيرك يعاني من نفس المشكة ولكن خلال السنتين ونصف من عمر البرنامج لم يبلغني احد بهذه المشكلة ... ولهذا انا اشكرك لانك اخبرتني عن مشكلتك

هذا الملف ضعه بدل الملف القديم الذي يحمل نفس الاسم
https://gofile.io/d/U765sW

اما مكان الملف فانا لست متأكد منه لانه يتغير مع كل تثبيت ولكن في حالتك اظن انه
/private/var/mobile/Containers/Data/Application/C806E156-512C-4B60-AD7C-36567EF5BB19/Library/Preferences/Kodi/addons/plugin.video.arabicvideos/arabicvideos/LIBRARY.py

اذا لم تجده هناك فاذن ابحث عنه هنا
addons/plugin.video.arabicvideos/arabicvideos/LIBRARY.py

===================
===================

سؤال ... انا بحاجة الى شخص لديه حساب ابل ويستطيع توقيع وتوثيق برامج ابل ... وذلك لعمل ملف خاص بتثبيت كودي ومدمج معه برنامجي ... لكي يستطيع جميع الناس تثبيت برنامجي وتثبيت كودي بدون الحاجة الى اي خبرة تقنية ... هذه القصة عملتها انا مع ويندوز ومع اندرويد ... وتستطيع زيارة هذا الموقع وتقرأ اكثر عن محتويات الملف ... علما ان ملفات ابل متوفرة عندي ولكن ابل لا تسمح بتوقيع الملف مجانا ولهذا ابحث عن شخص لديه اشتراك بدلا من ان اقوم بشراء اشتراك جديد ب 99 دولار

هنا تجد ملفات ويندوز واندرويد
http://tiny.cc/kodiemad

.

**Comment by emadmahdi** [comment]
هذا الملف انت تحتاجه فقط الان لكي تستخدمه مع الاصدار رقم 8.0.4 ... اما الاصدارات الجديدة القادمة فانك لن تحتاج هذا الملف لاني سوف اقوم باضافاته اوتوماتيكيا الى برنامجي

**Comment by amsmadi** [comment]
عاجز عن الشكر اخ عماد
بعد تبديل الملف الجديد بالقديم
الان الاضافة تعمل بشكل كامل

**Comment by amsmadi** [comment]
بخصوص توثيق برامج آبل
للاسف لا تستطيع توثيق البرنامج للجميع من خلال حساب 99 دولار وهو ما يسمى
individual developer account
ومن خلال هذا النوع من الحسابات يجب رفع البرنامج الى 
apple store
حتى يستطيع الجميع تنزيل البرنامج او توثيق نسخة وارسالها الى 100 شخص كحد اعلى وبشرط الحصول مسبقا على ارقام
udid
لهذه الاجهزة.

ما تبحث عنه انت تستطيع عمله فقط من خلال حساب يسمى
Developer Enterprise Program
بحيث يتم توثيق النسخة ونشرها من خلال الانترنت للجميع دون استثناء، ومشكلة هذا النوع من الحسابات موجود فقط بالشركات الكبيرة.

**Comment by emadmahdi** [comment]
انا غير قادر ان افهم ... كيف شركة ضخمة مثل ابل تمنع الميرمجين من تطوير برامج لاجهزتهم

لو كان هذا التصرف هو لحماية متجر ابل فهذا منطقي ولكن انا لا احتاج حتى المتجر ... فلماذا يمنعوني من نشر برامج تنفع أجهزتهم وترفع قيمتها عند المستخدمين ... هل انت متأكد انه لا يوجد حل لهذه المشكلة

خذ مثال ... لو هناك شخص يريد ان يشتري
tvbox
لكي يستخدمه مع برنامجي ... فهل يشتري جهاز ابل وهو يعرف ان برنامجي لا يعمل عنده ... ام يشتري جهاز اندرويد وهو يغرف ان برنامجي ينزل على اندرويد بكل سهولة .. اكيد سوف يختار جهاز اندرويد وخاصة انه ارخص بكثير من جهاز ابل
